<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4UMhqNj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4UMhqNj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4UMhqNj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4UMhqNj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4UMhqNj\App_KernelDevDebugContainer([
    'container.build_hash' => '4UMhqNj',
    'container.build_id' => '19e95249',
    'container.build_time' => 1658499131,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4UMhqNj');
