<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'pagamentos_index' => [['credencial', 'chave'], ['_controller' => 'App\\Controller\\ApiController::index'], [], [['text', '/'], ['variable', '/', '[^/]++', 'chave', true], ['variable', '/', '[^/]++', 'credencial', true], ['text', '/api/pagamentos']], [], [], []],
    'pagamento_pagamentos' => [['credencial', 'chave', 'identificador'], ['_controller' => 'App\\Controller\\ApiController::pagamentos'], [], [['variable', '/', '[^/]++', 'identificador', true], ['variable', '/', '[^/]++', 'chave', true], ['variable', '/', '[^/]++', 'credencial', true], ['text', '/api/pagamentos']], [], [], []],
    'pagamento_create' => [['credencial', 'chave'], ['_controller' => 'App\\Controller\\ApiController::create'], [], [['variable', '/', '[^/]++', 'chave', true], ['variable', '/', '[^/]++', 'credencial', true], ['text', '/api/pagamentos']], [], [], []],
    'pagamento_update' => [['credencial', 'chave', 'identificador'], ['_controller' => 'App\\Controller\\ApiController::update'], [], [['variable', '/', '[^/]++', 'identificador', true], ['variable', '/', '[^/]++', 'chave', true], ['variable', '/', '[^/]++', 'credencial', true], ['text', '/api/pagamentos']], [], [], []],
    'pagamento_delete' => [['credencial', 'chave', 'identificador'], ['_controller' => 'App\\Controller\\ApiController::delete'], [], [['variable', '/', '[^/]++', 'identificador', true], ['variable', '/', '[^/]++', 'chave', true], ['variable', '/', '[^/]++', 'credencial', true], ['text', '/api/pagamentos']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
];
